import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const nav=[['dashboard','Dashboard'],['coach','AI Coach'],['equipment','Workout Plan'],['exercises','Exercises'],['progress','Progress'],['progress','Body Metrics'],['analysis','History'],['analysis','Settings']];
const ex=['Barbell Bench Press','Lat Pulldown','Romanian Deadlift','Cable Face Pull','Goblet Squat','Dumbbell Lateral Raise'];
function Card({children,c=''}){return <section className={'card '+c}>{children}</section>}function Header({t,s}){return <header><h1>{t}</h1><p>{s}</p></header>}
function Side({p,set}){return <aside><h2><i>ϟ</i>ForgeFit</h2>{nav.map(([x,n])=><button className={p===x?'on':''} onClick={()=>set(x)}>◈　{n}</button>)}<div className="user">●　<b>Ron Forge</b><small>Premium Member</small></div></aside>}
function Dashboard(){return <><Header t="Ready to train, Ron?" s="Your custom upper body progression is generated and ready to go."/><div className="two"><Card><label>TODAY'S PLAN</label><h1>Upper Body Power</h1><p>Chest, Shoulders & Triceps • 45 min</p><div className="pills">Bench Press　 Overhead Press　 Lateral Raise</div><button className="primary">▷ Start Workout</button></Card><Card><h3>● AI Workout Coach</h3><p className="bubble">How should I modify my bench press for a shoulder injury?</p><p className="bubble">Use a neutral grip DB press or floor press instead.</p></Card></div><div className="four">{['Scan Gym Equipment','Active Pose Coach','Exercise Catalog','Start Guided Warm Up'].map(x=><Card><b>{x}</b><small>Explore & start</small></Card>)}</div><div className="two"><Card><h3>Anatomical Muscle Heatmap</h3><div className="body">●<br/>▰<br/>▥</div></Card><Card><h3>Weekly Progression</h3><div className="bars"/></Card></div></>}
function Coach(){return <><Header t="AI Pose Coach" s="Pose tracking calibrated. Start your reps with camera frame center."/><div className="coach"><div className="camera"><b>• FEEDBACK LIVE</b><div className="pose">╲━╱<br/>　┃<br/> ╱ ╲<br/>┃　┃</div><div className="cue">Movement Phase:　<b>Eccentric ↓</b>　<span>✓ Good depth</span></div></div><Card><h3>CURRENT FORM SCORE</h3><div className="ring">85</div>{['ROM 90%','Form Stability 82%','Exercise Tempo 88%','Symmetry 79%','Technique 91%'].map(x=><p className="metric">{x}<i/></p>)}</Card></div></>}
function Equipment(){return <><Header t="Scan Your Equipment" s="Point your camera at any gym station or dumbbell layout for instant AI detection."/><div className="coach"><div className="camera scan">⌜　　　　　　　　　⌝<strong>Detecting Cable Pulley...</strong>⌞　　　　　　　　　⌟</div><Card><h3>Suggested Exercises</h3>{['Lat Pulldown','Close Grip Cable Row','Cable Face Pull','Tricep Pushdown'].map(x=><p className="row"><b>{x}</b><small>Beginner</small></p>)}</Card></div><Card><h2>Cable Day — Upper Body Focus</h2><p>40 mins　 4 Stations　 Back, Shoulders & Arms</p><button className="primary">Start This Workout</button></Card></>}
function Exercises(){return <><Header t="Exercises" s="Explore our dynamic library of movements with real-time AI guidance setup."/><div className="filters">All　 Chest　 Back　 Shoulders　 Arms　 Legs　 Core</div><div className="grid">{ex.map(x=><Card><div className="media">AI COACH　▶</div><small>Barbell</small><h3>{x}</h3><span>Chest　 Shoulders</span></Card>)}</div></>}
function Progress(){return <><Header t="Progress & Body Metrics" s="Review muscle load distributions, training frequencies, and strength projections."/><div className="two"><Card><h2>Anatomical Muscle Heatmap</h2><div className="body big">●<br/>▰<br/>▥</div></Card><Card><h2>Chest</h2><h1>24　 8,400 kg</h1>{['Bench Press (12 sets)','Incline DB Press (8 sets)','Cable Fly (4 sets)'].map(x=><p className="row">{x}</p>)}</Card></div><div className="two"><Card><h3>Training Calendar</h3><div className="calendar">{Array.from({length:28},(_,i)=><b>{i+1}</b>)}</div></Card><Card><h3>Strength Trends (1RM)</h3><div className="chart">╱╲╱╲╱</div></Card></div></>}
function Analysis(){return <><Header t="Workout Complete!" s="Sensors synced. Your pose consistency today was outstanding."/><div className="four">{[['Duration','47 min'],['Total Sets','24'],['Total Reps','186'],['Volume','12,840 kg']].map(x=><Card><small>{x[0]}</small><h1>{x[1]}</h1></Card>)}</div><div className="two"><Card><h1>⚡ 420 kcal</h1><p>Estimated Active Burn</p></Card><Card><h1>87　Excellent Form</h1><p>✓ 0 critical breakdowns detected</p></Card></div><div className="two"><Card><h3>Trained Muscle Heatmap</h3><div className="body">●<br/>▰<br/>▥</div></Card><Card><h3>AI Technique Feedback</h3>{['Excellent squat depth maintained','Bench press bar path improved','Right shoulder elevation detected','Deadlift hip hinge mechanics are solid'].map(x=><p className="row">●　{x}</p>)}</Card></div></>}
function App(){let[p,set]=useState('dashboard');let V={dashboard:<Dashboard/>,coach:<Coach/>,equipment:<Equipment/>,exercises:<Exercises/>,progress:<Progress/>,analysis:<Analysis/>};return <div className="app"><Side p={p} set={set}/><main><div className="page">{V[p]}</div></main></div>}createRoot(document.getElementById('root')).render(<App/>);
